language: objective-c
osx_image: xcode8.3

branches:
  only:
    - master

env:
  global:
    - NODE_VERSION=stable

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - npm install -g yarn

install:
  - brew tap wix/brew
  - brew install applesimutils
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
  - export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - nvm alias default $NODE_VERSION
  - yarn

script:
  - yarn e2e:ci
